version: '3' 
services:
  redis5:
    image: redis:5.0.6
    container_name: redis5
    volumes:
      - ${PWD}/data:/data
    environment:
      - REDIS_DATA_DIR=/data/
    healthcheck:
      interval: 5s
      retries: 10
    ports:
      - 6379:6379
    networks:
      - odsc-network
    hostname: "redis5"
  zeppelin:
    image: apache/zeppelin:0.8.1
    container_name: zeppelin
    volumes:
      - ${PWD}/notebook:/notebook
      - ${PWD}/logs:/logs
      - ${PWD}/data:/odsc
      - ${PWD}/spark-2.4.4:/spark
    environment:
      - SPARK_HOME=/spark
      - ZEPPELIN_LOG_DIR=/logs/
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
    healthcheck:
      interval: 5s
      retries: 10
    ports:
      - 8080:8080
      - 4040:4040
    depends_on:
      - redis5
    networks:
      - odsc-network
    hostname: "zeppelin"

networks:
  odsc-network:
    external:
      name: odsc-network